CREATE TABLE IF NOT EXISTS CUSTOMER (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(255) NOT NULL,
    MIDDLE_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PHONE_NUMBER TEXT NOT NULL,
    CREATED_DATE TIMESTAMP,
    UPDATED_DATE TIMESTAMP
);

COMMENT ON COLUMN CUSTOMER.ID IS E'Ideally it should be GUID. But kept it as Integer for simplicity.';