
spring:
  application:
    name: customer-service-app
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operationsSorter: method
server:
  shutdown: graceful
management:
  endpoints:
    web:
      exposure:
        include: health, refresh,liveness,readiness